# Generated by Django 4.2.17 on 2024-12-25 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_airline', '0011_scheduledflights_is_active'),
        ('app_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlivery',
            name='designator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_airline.fleet', verbose_name='Designator'),
        ),
    ]
