# Generated by Django 4.2.17 on 2024-12-15 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=100, unique=True, verbose_name='Network Name')),
                ('network_abbr', models.CharField(help_text='IVAO / VATSIM etc.', max_length=10, verbose_name='Network Abbr.')),
                ('network_url', models.URLField(blank=True, null=True, verbose_name='Network Link')),
                ('network_logo', models.ImageField(blank=True, help_text='Image Size: 450x150 px.', null=True, upload_to='uploads/airline/images/partners', verbose_name='Network Logo')),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Networks',
            },
        ),
        migrations.CreateModel(
            name='PilotBadges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_order', models.SmallIntegerField(default=1, verbose_name='Order')),
                ('pilot_title', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Title')),
                ('pilot_title_abbr', models.CharField(max_length=5, unique=True, verbose_name='Title Abbr')),
                ('pilot_badge', models.ImageField(blank=True, help_text='IVAO ATC Badges', null=True, upload_to='uploads/airline/images/badges/ivao/pilot', verbose_name='Badge')),
                ('network_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.networks', verbose_name='Network')),
            ],
            options={
                'verbose_name': 'Pilot Badge',
                'verbose_name_plural': 'Pilot Badges',
            },
        ),
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Division Name')),
                ('division_abbr', models.CharField(max_length=2, verbose_name='Division Abbr.')),
                ('network_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.networks', verbose_name='Network')),
            ],
            options={
                'verbose_name': 'IVAO Division',
                'verbose_name_plural': 'IVAO Divisions',
            },
        ),
        migrations.CreateModel(
            name='ATCBadges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_order', models.SmallIntegerField(default=1, verbose_name='Order')),
                ('atc_title', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Title')),
                ('atc_title_abbr', models.CharField(max_length=5, unique=True, verbose_name='Title Abbr')),
                ('atc_badge', models.ImageField(blank=True, help_text='IVAO ATC Badges', null=True, upload_to='uploads/airline/images/badges/ivao/atc', verbose_name='Badge')),
                ('network_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_database.networks', verbose_name='Network')),
            ],
            options={
                'verbose_name': 'ATC Badge',
                'verbose_name_plural': 'ATC Badges',
            },
        ),
    ]
