# Generated by Django 4.2.17 on 2024-12-15 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOnline', models.BooleanField(default=True, verbose_name='Website is Online')),
                ('airline_longName', models.CharField(max_length=100, unique=True, verbose_name='Airline Name')),
                ('airline_shortName', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Airline Short Name')),
                ('airline_sloganFirstLine', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slogan First Line')),
                ('airline_slogan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Slogan')),
                ('airline_about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('airline_established', models.DateField(blank=True, null=True, verbose_name='Established on')),
                ('airline_icao', models.CharField(max_length=3, unique=True, verbose_name='ICAO Designator')),
                ('airline_iata', models.CharField(max_length=2, unique=True, verbose_name='IATA Designator')),
                ('airline_url', models.URLField(verbose_name='URL')),
                ('airline_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('airline_staff_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail (STAFF)')),
                ('airline_noreply_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail (No Reply)')),
                ('airline_logo', models.ImageField(blank=True, help_text='Airline main logo for DARK backgrounds', null=True, upload_to='uploads/airline/images/main/logos', verbose_name='Logo')),
                ('airline_web_copyright', models.CharField(blank=True, max_length=250, null=True, verbose_name='Copyright')),
                ('airline_web_warning', models.CharField(blank=True, help_text='Warning for not real airline', max_length=250, null=True, verbose_name='Web Warning')),
            ],
            options={
                'verbose_name': 'Airline Setting',
                'verbose_name_plural': 'Airline Settings',
            },
        ),
        migrations.CreateModel(
            name='BaseHubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=1, verbose_name='Fleet Order')),
                ('airport', models.CharField(help_text='Esenboga International Airport', max_length=100, verbose_name='Airport')),
                ('city', models.CharField(help_text='Ankara', max_length=50, verbose_name='Airport City')),
                ('icao', models.CharField(help_text='LTAC', max_length=4, verbose_name='Airport ICAO')),
                ('iata', models.CharField(help_text='ESB', max_length=3, verbose_name='Airport IATA')),
                ('is_base', models.BooleanField(default=False, verbose_name='Base Airport')),
                ('is_hub', models.BooleanField(default=False, verbose_name='Hub Airport')),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
            },
        ),
        migrations.CreateModel(
            name='FaqCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_order', models.SmallIntegerField(default=1, verbose_name='Order')),
                ('cat_name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('cat_icon', models.CharField(help_text='fontawesome icon or others', max_length=100, verbose_name='Category Icon')),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
            },
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=1, verbose_name='Fleet Order')),
                ('name', models.CharField(help_text='Boeing 737-600', max_length=100, verbose_name='Fleet Name')),
                ('designator', models.CharField(help_text='B736', max_length=5, verbose_name='Designator')),
                ('publisher', models.CharField(max_length=100, verbose_name='Publisher')),
                ('publisher_url', models.URLField(verbose_name='Publisher URL')),
                ('publisher_logo', models.ImageField(blank=True, null=True, upload_to='uploads/airline/fleet/images', verbose_name='Publisher Logo')),
            ],
            options={
                'verbose_name': 'Fleet',
                'verbose_name_plural': 'Fleets',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField(verbose_name='News')),
                ('news_img', models.ImageField(blank=True, help_text='Use 16:9 resolution images.', null=True, upload_to='uploads/airline/news/images', verbose_name='News Image')),
                ('news_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('is_published', models.BooleanField(default=False, verbose_name='is Published')),
            ],
            options={
                'verbose_name': 'Skylink News',
                'verbose_name_plural': 'Skylink News',
            },
        ),
        migrations.CreateModel(
            name='StaffPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_order', models.SmallIntegerField(default=1, verbose_name='Order #')),
                ('staff_title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('staff_title_abbr', models.CharField(max_length=5, unique=True, verbose_name='Abbr.')),
                ('staff_position_brief', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brief Description of Position')),
                ('staff_job_description', models.TextField(blank=True, null=True, verbose_name='Job Description')),
                ('staff_job_specification', models.TextField(blank=True, null=True, verbose_name='Job Specification')),
                ('staff_pos_hiring', models.BooleanField(default=False, verbose_name='Hiring')),
                ('staff_pos_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Staff E-mail')),
                ('airline_shortName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_airline.airline', verbose_name='Airline')),
            ],
            options={
                'verbose_name': 'Staff Position',
                'verbose_name_plural': 'Staff Positions',
            },
        ),
        migrations.CreateModel(
            name='StaffPositionRevisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spr_title', models.CharField(max_length=50, verbose_name='Revision Title')),
                ('spr_content', models.TextField(verbose_name='Content')),
                ('spr_date', models.DateField(verbose_name='Date')),
                ('spr_isPublished', models.BooleanField(default=False, verbose_name='is Published')),
                ('staff_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_airline.staffpositions', verbose_name='Staff Position')),
            ],
            options={
                'verbose_name': 'Staff Position',
                'verbose_name_plural': 'Staff Positions',
            },
        ),
        migrations.CreateModel(
            name='Scenery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/airline/basehubs/scenery/images', verbose_name='Scenery Image')),
                ('publisher', models.CharField(max_length=100, verbose_name='Publisher')),
                ('publisher_url', models.URLField(verbose_name='Publisher URL')),
                ('is_free', models.BooleanField(default=False, verbose_name='Free')),
                ('is_payware', models.BooleanField(default=False, verbose_name='Payware')),
                ('supports', models.CharField(help_text='MSFS20 & MSFS24', max_length=100, verbose_name='Supports')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_airline.basehubs', verbose_name='Airport')),
            ],
            options={
                'verbose_name': 'Scenery',
                'verbose_name_plural': 'Sceneries',
            },
        ),
        migrations.CreateModel(
            name='Partnerships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_order', models.SmallIntegerField(default=1, verbose_name='Order')),
                ('partner_longName', models.CharField(max_length=100, unique=True, verbose_name='Partner')),
                ('partner_shortName', models.CharField(max_length=10, unique=True, verbose_name='Partner Abbr.')),
                ('partner_logo', models.ImageField(blank=True, help_text='Canvas size: 450x150px', null=True, upload_to='uploads/airline/images/main/partners', verbose_name='Partner Logo')),
                ('partner_URL', models.URLField(verbose_name='Partner URL')),
                ('partner_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Partner E-mail')),
                ('partner_since', models.DateField(blank=True, null=True, verbose_name='Partner Since')),
                ('partner_active', models.BooleanField(default=False, verbose_name='Partnership is approved')),
                ('airline_shortName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_airline.airline', verbose_name='Airline')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_order', models.SmallIntegerField(default=1, verbose_name='Order')),
                ('offer_icon', models.CharField(blank=True, help_text='Favicon or others can be used', max_length=50, null=True, verbose_name='Icon')),
                ('offer_title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('offer_content', models.TextField(help_text='What we offer description', verbose_name='Content')),
                ('offer_published', models.BooleanField(default=False, verbose_name='is Published')),
                ('airline_shortName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_airline.airline', verbose_name='Airline')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_order', models.SmallIntegerField(default=1, verbose_name='Order')),
                ('faq_question', models.CharField(blank=True, max_length=250, null=True, verbose_name='Question')),
                ('faq_answer', models.TextField(verbose_name='Answer')),
                ('cat_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_airline.faqcategories', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'FAQ - Frequently Asked Question',
                'verbose_name_plural': 'FAQ - Frequently Asked Questions',
            },
        ),
        migrations.CreateModel(
            name='AirlineLandingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_landing_image', models.ImageField(blank=True, help_text='3840x1500px', null=True, upload_to='uploads/airline/images/main/landing', verbose_name='Landing Page Image')),
                ('is_Published', models.BooleanField(default=False, verbose_name='is Published?')),
                ('airline_shortName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_airline.airline', verbose_name='Airline')),
            ],
            options={
                'verbose_name': 'Airline Landing_Image',
                'verbose_name_plural': 'Airline Landing Images',
            },
        ),
        migrations.CreateModel(
            name='AirlineBadges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_order', models.SmallIntegerField(default=1, verbose_name='Order #')),
                ('pilot_title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('pilot_title_abbr', models.CharField(max_length=5, unique=True, verbose_name='Title Abbr')),
                ('pilot_badge', models.ImageField(blank=True, null=True, upload_to='uploads/airline/badges/airline/pilot', verbose_name='Badge')),
                ('req_hours', models.SmallIntegerField(default=0, verbose_name='Hours')),
                ('req_pireps', models.SmallIntegerField(default=0, verbose_name='PIREPS')),
                ('req_points', models.SmallIntegerField(default=0, verbose_name='Points')),
                ('req_bonus_points', models.SmallIntegerField(default=0, verbose_name='Bonus Points')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('airline_shortName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_airline.airline', verbose_name='Airline')),
                ('req_atc_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_database.atcbadges', verbose_name='Required ATC Badge')),
                ('req_pilot_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_database.pilotbadges', verbose_name='Required Pilot Badge')),
            ],
            options={
                'verbose_name': 'Airline Pilot Badge',
                'verbose_name_plural': 'Airline Pilot Badges',
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('registration', models.CharField(help_text='TC-SLA', max_length=10, unique=True, verbose_name='Registration')),
                ('image', models.ImageField(blank=True, help_text='16:9 Resolution', null=True, upload_to='uploads/airline/fleet/airframe/images', verbose_name='Image')),
                ('description', models.TextField(blank=True, help_text='Some information about fleet', null=True, verbose_name='About Fleet')),
                ('is_commercial', models.BooleanField(default=False, verbose_name='Commercial')),
                ('is_charter', models.BooleanField(default=False, verbose_name='Charter')),
                ('is_cargo', models.BooleanField(default=False, verbose_name='Freighter')),
                ('is_training', models.BooleanField(default=False, verbose_name='Training')),
                ('livery_URL', models.URLField(verbose_name='Livery Download Link')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_airline.basehubs', verbose_name='Aircraft Base')),
                ('designator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_airline.fleet')),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircraft',
            },
        ),
    ]
