# Generated by Django 4.2.17 on 2024-12-16 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_airline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('link', models.URLField(verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
            },
        ),
        migrations.CreateModel(
            name='FlightOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Flight Operation',
                'verbose_name_plural': 'Flight Operations',
            },
        ),
        migrations.CreateModel(
            name='RankingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
            },
        ),
        migrations.CreateModel(
            name='RulesRegulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='RulesRegulationsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Update')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date Applied')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_airline.rulesregulations', verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Rule Update',
                'verbose_name_plural': 'Rule Updates',
            },
        ),
        migrations.CreateModel(
            name='RankingSystemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Update')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date Applied')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_airline.rankingsystem', verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Ranking System Update',
                'verbose_name_plural': 'Ranking System Updates',
            },
        ),
        migrations.CreateModel(
            name='FlightOperationsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Update')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date Applied')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_airline.flightoperations', verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Flight Operations Update',
                'verbose_name_plural': 'Flight Operations Updates',
            },
        ),
    ]
