# Generated by Django 4.2.17 on 2024-12-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_airline', '0003_rulesregulations_rules_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingsystem',
            name='ranking_order',
            field=models.SmallIntegerField(default=1, verbose_name='Ranking Order'),
        ),
    ]
