# Generated by Django 4.2.17 on 2024-12-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_airline', '0005_basehubs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='basehubs',
            name='is_cargo',
            field=models.BooleanField(default=False, verbose_name='Scheduled'),
        ),
        migrations.AddField(
            model_name='basehubs',
            name='is_charter',
            field=models.BooleanField(default=True, verbose_name='Scheduled'),
        ),
        migrations.AddField(
            model_name='basehubs',
            name='is_scheduled',
            field=models.BooleanField(default=False, verbose_name='Scheduled'),
        ),
    ]
