# Generated by Django 4.2.17 on 2024-12-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_airline', '0006_basehubs_is_cargo_basehubs_is_charter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basehubs',
            name='link',
            field=models.URLField(blank=True, help_text='https://en.wikipedia.org/wiki/Istanbul_Airport', null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='basehubs',
            name='is_cargo',
            field=models.BooleanField(default=False, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='basehubs',
            name='is_charter',
            field=models.BooleanField(default=True, verbose_name='Charter'),
        ),
    ]
