# Generated by Django 4.2.17 on 2024-12-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_airline', '0007_basehubs_link_alter_basehubs_is_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='type_of_flight',
            field=models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('Charter', 'Charter'), ('Cargo', 'Cargo'), ('General Aviation', 'General Aviation')], default='Charter', max_length=30, null=True, verbose_name='Type of Flight'),
        ),
    ]
