# Generated by Django 4.2.17 on 2024-12-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_airline', '0008_aircraft_type_of_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='engine_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Engine Type'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='max_passengers',
            field=models.SmallIntegerField(default=1, verbose_name='Maximum Passengers'),
        ),
    ]
