# Generated by Django 4.2.17 on 2024-12-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_airline', '0010_scheduledflights'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledflights',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is Active'),
        ),
    ]
