# Generated by Django 4.2.17 on 2024-12-25 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_airline', '0011_scheduledflights_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(verbose_name='Order')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_airline.airline')),
            ],
            options={
                'verbose_name': 'Privacy Policy Title',
                'verbose_name_plural': 'Privacy Policy Titles',
            },
        ),
    ]
