# Generated by Django 4.2.17 on 2024-12-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_airline', '0012_privacypolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicy',
            name='airline',
        ),
    ]
