# Generated by Django 4.2.17 on 2024-12-23 05:50

import app_community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshots',
            old_name='is_Published',
            new_name='is_published',
        ),
        migrations.AddField(
            model_name='screenshots',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='is Approved'),
        ),
        migrations.AlterField(
            model_name='screenshots',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='members/uploads/screenshots/images', validators=[app_community.models.validate_aspect_ratio_16_9], verbose_name='Screenshot'),
        ),
    ]
