# Generated by Django 4.2.17 on 2024-12-24 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_airline', '0011_scheduledflights_is_active'),
        ('app_community', '0003_remove_screenshots_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Requested By')),
                ('flight_type', models.CharField(choices=[('1', 'Charter'), ('2', 'Cargo')], max_length=10, verbose_name='Flight Type')),
                ('arrival', models.CharField(max_length=4, verbose_name='Arrival ICAO')),
                ('purpose', models.TextField(verbose_name='Purpose of Flight')),
                ('aircraft_type', models.CharField(max_length=4, verbose_name='Aircraft Designator')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='Requested on')),
                ('is_approved', models.BooleanField(default=False, verbose_name='is Approved')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_airline.basehubs', verbose_name='Departure')),
            ],
            options={
                'verbose_name': 'Route Request',
                'verbose_name_plural': 'Requests',
            },
        ),
    ]
