# Generated by Django 4.2.17 on 2024-12-24 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_airline', '0011_scheduledflights_is_active'),
        ('app_community', '0004_requestroute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestroute',
            options={'verbose_name': 'Route Request', 'verbose_name_plural': 'Route Requests'},
        ),
        migrations.RemoveField(
            model_name='requestroute',
            name='aircraft_type',
        ),
        migrations.AddField(
            model_name='requestroute',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_airline.fleet', verbose_name='Aircraft'),
        ),
        migrations.AlterField(
            model_name='requestroute',
            name='departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_airline.basehubs', verbose_name='Departure'),
        ),
    ]
