# Generated by Django 4.2.17 on 2024-12-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_community', '0005_alter_requestroute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestroute',
            name='date_of_flight',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Flight'),
        ),
    ]
