# Generated by Django 4.2.17 on 2024-12-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_community', '0006_requestroute_date_of_flight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestRoute',
        ),
    ]
