# Generated by Django 4.2.17 on 2024-12-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='division_name',
        ),
    ]
