# Generated by Django 4.2.17 on 2024-12-15 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_airline', '0001_initial'),
        ('app_database', '0001_initial'),
        ('app_users', '0002_remove_customuser_division_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='division_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_database.divisions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pilot_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_airline.airlinebadges', verbose_name='Pilot Rank'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='staff_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_airline.staffpositions', verbose_name='Staff Position'),
        ),
    ]
