# Generated by Django 4.2.17 on 2024-12-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_customuser_division_name_customuser_pilot_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='twitch_creator',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='youtube_creator',
        ),
    ]
