# Generated by Django 4.2.17 on 2024-12-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_remove_customuser_twitch_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
