# Generated by Django 4.2.17 on 2024-12-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_events', '0003_skylinkevents_remove_hqevents_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hqevents',
            name='airports',
        ),
        migrations.RemoveField(
            model_name='hqevents',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='hqevents',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='hqevents',
            name='type',
        ),
        migrations.RemoveField(
            model_name='skylinkevents',
            name='airports',
        ),
        migrations.RemoveField(
            model_name='skylinkevents',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='skylinkevents',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='skylinkevents',
            name='type',
        ),
        migrations.RemoveField(
            model_name='trevents',
            name='airports',
        ),
        migrations.RemoveField(
            model_name='trevents',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trevents',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='trevents',
            name='type',
        ),
        migrations.AddField(
            model_name='hqevents',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/airline/events/HQ', verbose_name='Event Image'),
        ),
        migrations.AddField(
            model_name='skylinkevents',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/airline/events/SKYLINK', verbose_name='Event Image'),
        ),
        migrations.AddField(
            model_name='trevents',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/airline/events/TR', verbose_name='Event Image'),
        ),
    ]
