# Generated by Django 4.2.17 on 2024-12-18 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_events', '0004_remove_hqevents_airports_remove_hqevents_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='uploads/airline/events', verbose_name='Event Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('event_url', models.URLField(blank=True, max_length=100, null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'HQ Event',
                'verbose_name_plural': 'HQ Events',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Event Type')),
                ('type_image', models.ImageField(blank=True, null=True, upload_to='uploads/airline/events/types', verbose_name='Event Owner Image')),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
            },
        ),
        migrations.DeleteModel(
            name='HQEvents',
        ),
        migrations.DeleteModel(
            name='TREvents',
        ),
        migrations.AlterModelOptions(
            name='skylinkevents',
            options={'verbose_name': 'Skylink Event', 'verbose_name_plural': 'Skylink Events'},
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_events.eventtype', verbose_name='Event Type'),
        ),
    ]
